language: cpp

compiler:
  - clang
  - g++

env:
  - CONFIG=debug
  - CONFIG=release

before_install:
  - travis_retry sudo add-apt-repository -y ppa:beineri/opt-qt532
  - travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - travis_retry sudo apt-get update -qq

install:
  - travis_retry if [ "$CXX" == "g++" ]; then sudo apt-get -qq install g++-4.8; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - travis_retry sudo apt-get install -qq qt53tools qt53base
  - travis_retry sudo apt-get install -qq libopenbabel-dev
    
before_script:
  - source /opt/qt53/bin/qt53-env.sh
  - if [ "$CXX" == "clang++" ]; then SPEC="linux-clang"; else SPEC="linux-g++"; fi

script:
  - qmake -v
  - $CXX -v
  - qmake -r -spec $SPEC CONFIG+=$CONFIG
  - make